-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text,
  address_line_2 text,
  city text,
  state text,
  zipcode text,
  country text DEFAULT 'USA'::text,
  company_code text NOT NULL UNIQUE,
  phone text,
  email text,
  website text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  hire_date date NOT NULL,
  termination_date date,
  job_title text,
  department text,
  employment_status USER-DEFINED NOT NULL DEFAULT 'active'::employment_status,
  is_manager boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approval_status text NOT NULL DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  work_status text NOT NULL DEFAULT 'available'::text CHECK (work_status = ANY (ARRAY['available'::text, 'inactive'::text, 'vacation'::text, 'sick'::text])),
  CONSTRAINT company_employees_pkey PRIMARY KEY (id),
  CONSTRAINT company_employees_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_employees_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.company_owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  ownership_percentage numeric,
  is_primary_owner boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_owners_pkey PRIMARY KEY (id),
  CONSTRAINT company_owners_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_owners_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.customer_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  name text NOT NULL,
  role text,
  phone text,
  email text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT customer_contacts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  billing_address text,
  billing_address_line_2 text,
  billing_city text,
  billing_state text,
  billing_zipcode text,
  billing_country text DEFAULT 'USA'::text,
  service_address text,
  service_address_line_2 text,
  service_city text,
  service_state text,
  service_zipcode text,
  service_country text DEFAULT 'USA'::text,
  same_as_billing boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.job_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  job_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  service_start_at timestamp with time zone,
  service_end_at timestamp with time zone,
  assignment_status text NOT NULL DEFAULT 'assigned'::text CHECK (assignment_status = ANY (ARRAY['assigned'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text])),
  worker_confirmed_done_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT job_assignments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT job_assignments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_assignments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.company_employees(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  title text NOT NULL,
  summary text,
  service_address text,
  service_address_line_2 text,
  service_city text,
  service_state text,
  service_zipcode text,
  service_country text DEFAULT 'USA'::text,
  tasks_to_complete text,
  status text NOT NULL DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text])),
  planned_end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  phone text,
  email text,
  address text,
  address_line_2 text,
  city text,
  state text,
  zipcode text,
  country text DEFAULT 'USA'::text,
  avatar_url text,
  timezone text DEFAULT 'America/New_York'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);