-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  address text,
  address_line_2 text,
  city text,
  state text,
  zipcode text,
  country text DEFAULT 'USA'::text,
  company_code text NOT NULL UNIQUE,
  phone text,
  email text,
  website text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  logo_url text,
  show_address_on_invoice boolean DEFAULT true,
  CONSTRAINT companies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.company_accountants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE,
  accountant_name text,
  accountant_email text,
  accountant_phone text,
  accountant_address text,
  accountant_address_line_2 text,
  accountant_city text,
  accountant_state text,
  accountant_zipcode text,
  accountant_country text DEFAULT 'USA'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_accountants_pkey PRIMARY KEY (id),
  CONSTRAINT company_accountants_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.company_employees (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  hire_date date NOT NULL,
  termination_date date,
  job_title text,
  department text,
  employment_status USER-DEFINED NOT NULL DEFAULT 'active'::employment_status,
  is_manager boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  approval_status text NOT NULL DEFAULT 'pending'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  work_status text NOT NULL DEFAULT 'available'::text CHECK (work_status = ANY (ARRAY['available'::text, 'inactive'::text, 'vacation'::text, 'sick'::text])),
  CONSTRAINT company_employees_pkey PRIMARY KEY (id),
  CONSTRAINT company_employees_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_employees_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.company_invoice_counters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL UNIQUE,
  last_number integer NOT NULL DEFAULT 10000,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_invoice_counters_pkey PRIMARY KEY (id),
  CONSTRAINT company_invoice_counters_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.company_owners (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  profile_id uuid NOT NULL,
  ownership_percentage numeric,
  is_primary_owner boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_owners_pkey PRIMARY KEY (id),
  CONSTRAINT company_owners_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_owners_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.customer_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  name text NOT NULL,
  role text,
  phone text,
  email text,
  is_primary boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT customer_contacts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name text NOT NULL,
  phone text,
  email text,
  billing_address text,
  billing_address_line_2 text,
  billing_city text,
  billing_state text,
  billing_zipcode text,
  billing_country text DEFAULT 'USA'::text,
  service_address text,
  service_address_line_2 text,
  service_city text,
  service_state text,
  service_zipcode text,
  service_country text DEFAULT 'USA'::text,
  same_as_billing boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.invoice_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  line_number integer NOT NULL,
  line_type USER-DEFINED NOT NULL DEFAULT 'service'::invoice_line_type,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL,
  line_total numeric DEFAULT (quantity * unit_price),
  taxable boolean DEFAULT true,
  tax_rate numeric DEFAULT 0,
  applied_payment_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  job_id uuid,
  CONSTRAINT invoice_lines_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_lines_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT invoice_lines_applied_payment_id_fkey FOREIGN KEY (applied_payment_id) REFERENCES public.payments(id),
  CONSTRAINT invoice_lines_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  job_id uuid,
  invoice_number text NOT NULL,
  invoice_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::invoice_status,
  tax_amount numeric DEFAULT 0,
  notes text,
  terms text,
  issued_at timestamp with time zone,
  paid_at timestamp with time zone,
  voided_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  total_amount numeric DEFAULT 0,
  subtotal numeric DEFAULT 0,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT invoices_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.job_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  job_id uuid NOT NULL,
  employee_id uuid NOT NULL,
  service_start_at timestamp with time zone,
  service_end_at timestamp with time zone,
  assignment_status text NOT NULL DEFAULT 'assigned'::text CHECK (assignment_status = ANY (ARRAY['assigned'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text])),
  worker_confirmed_done_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT job_assignments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT job_assignments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id),
  CONSTRAINT job_assignments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.company_employees(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  title text NOT NULL,
  summary text,
  service_address text,
  service_address_line_2 text,
  service_city text,
  service_state text,
  service_zipcode text,
  service_country text DEFAULT 'USA'::text,
  tasks_to_complete text,
  status text NOT NULL DEFAULT 'upcoming'::text CHECK (status = ANY (ARRAY['upcoming'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text])),
  planned_end_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  estimated_amount numeric DEFAULT 0,
  CONSTRAINT jobs_pkey PRIMARY KEY (id),
  CONSTRAINT jobs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT jobs_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.payment_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payment_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  applied_amount numeric NOT NULL CHECK (applied_amount > 0::numeric),
  applied_at timestamp with time zone DEFAULT now(),
  invoice_line_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  applied_by uuid,
  CONSTRAINT payment_applications_pkey PRIMARY KEY (id),
  CONSTRAINT payment_applications_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.payments(id),
  CONSTRAINT payment_applications_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payment_applications_invoice_line_id_fkey FOREIGN KEY (invoice_line_id) REFERENCES public.invoice_lines(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  job_id uuid,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_date date NOT NULL DEFAULT CURRENT_DATE,
  payment_method USER-DEFINED NOT NULL DEFAULT 'cash'::payment_method,
  reference_number text,
  memo text,
  is_deposit boolean NOT NULL DEFAULT false,
  deposit_type USER-DEFINED,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT payments_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT payments_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.jobs(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  phone text,
  email text,
  address text,
  address_line_2 text,
  city text,
  state text,
  zipcode text,
  country text DEFAULT 'USA'::text,
  avatar_url text,
  timezone text DEFAULT 'America/New_York'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.request_idempotency (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  idempotency_key text NOT NULL,
  route text NOT NULL,
  response_status integer NOT NULL,
  response_body jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT request_idempotency_pkey PRIMARY KEY (id)
);